apiVersion: apps/v1
kind: Deployment
metadata:
  name: techtrends
  namespace: sandbox
  labels:
    app: techtrends
spec:
  replicas: 1
  template:
    metadata:
      name: techtrends
      labels:
        app: techtrends
    spec:
      containers:
        - name: techtrends
          resources:
            requests:
              memory: '64Mi'
              cpu: '250m'
            limits:
              memory: '128Mi'
              cpu: '500m'
          image: codecritics/techtrends:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3111
          livenessProbe:
            httpGet:
              port: 3111
              path: /healthz
          readinessProbe:
            httpGet:
              port: 3111
              path: /healthz
      restartPolicy: Always
  selector:
    matchLabels:
      app: techtrends
